language: python
python:
  - "3.9"
sudo: false
cache:
  directories:
    - "~/.platformio"
    - $HOME/.cache/pip
install:
  - pip install -U platformio
  - pio update
before_script:
  - chmod +x ./.travis/test.sh
  - ./.travis/test.sh
script:
  - chmod +x ./.travis/build.sh
  - ./.travis/build.sh
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: htcw_gfx-*.tar.gz
  skip_cleanup: true
  on:
    tags: true
